import { Playfair_Display, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import ScrollProvider from "@/app/components/ScrollProvider";

// Assign fonts to properly named variables
const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  display: "swap", // optional: for better font rendering
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${playfairDisplay.variable} ${poppins.variable}`}>
      <body className="antialiased font-sans">
        <Navbar></Navbar>
        <ScrollProvider>{children}</ScrollProvider>
        <Footer></Footer>
      </body>
    </html>
  );
}

